### PR TITLE
Fix Targets

### PR DESCRIPTION
**Pull request by thehabes**
For #9.  You will notice I placed `/full/1000,/0/default.jpg` at the end of the service URIs.  We can change 1000 to whatever we want, even max if that's what we need `/full/max/0/default.jpg`.

### CODE REVIEW

**Comment by thehabes** [comment]
Takes care of #9

**Comment by bertspaan** [comment]
Seems strange... why not link to the image URI, without the region/size/quality part?

**Comment by thehabes** [comment]
Because the API says so...

If the content resource is an Image, and a IIIF Image service is available for it, then the id property of the content resource may be a complete URI to any particular representation supported by the Image Service, such as https://example.org/image1/full/1000,/0/default.jpg, but must not be just the URI of the IIIF Image service. Its type value must be the string Image. Its media type may be listed in format, and its height and width may be given as integer values for height and width respectively. The Image should have the service referenced from it using the service property.

**Comment by thehabes** [comment]
What you provided there, https://tile.loc.gov/image-services/iiif/service:gmd:gmd384:g3842:g3842c:ct008615, is a service, not an image URI.  When you resolve it, you get JSON not an image.  

`source` needs to be a link that resolves to an image, not JSON.  You do that using the service syntax and noting the service block.

**Comment by bertspaan** [comment]
🥴‼️

I have so much to learn about IIIF!

**Comment by thehabes** [comment]
Yep.  You will notice Recogito does it wrong and they should be sacked.

**Comment by thehabes** [comment]
Oooo they did it under the guise of prezi 2, which says

If a IIIF Image service is available for the image, then the URL may be the complete URL to a particular size of the image content, such as http://example.org/image1/full/1000,/0/default.jpg. It should have an @type of “dctypes:Image”. Its media type may be listed in format, and its height and width may be given as integer values for height and width respectively.

Notice that it does not say ` but must not be just the URI of the IIIF Image service`.  We won't sack them yet, but we want them to catch up to prezi 3

**Review by bertspaan — APPROVED** [review]

**Pull request merged**
